import type { BankQuestion } from "../twin/schema.ts";

// Question bank for building a digital twin of a UK university student applying to
// finance, economics and banking placements, internships and graduate schemes. Questions
// are kept broad enough to suit most careers. Ordering inside each section runs from
// factual to reflective to deep, so an interview can flow from easy to hard.

export const QUESTION_BANK: BankQuestion[] = [
  // ---------- identity ----------
  { id: "id-full-name", section: "identity", depth: 1, factKey: "full_name", tags: ["basics"],
    question: "What is your full name, as it appears on your passport or right-to-work documents?",
    hint: "Full legal name exactly as on ID, including any middle names. Note any preferred name separately." },
  { id: "id-email", section: "identity", depth: 1, factKey: "email", tags: ["basics", "contact"],
    question: "What email address do recruiters should use to reach you, and is it checked daily?",
    hint: "A personal, professional-looking address you check regularly. Avoid shared or old university aliases if you will leave soon." },
  { id: "id-phone", section: "identity", depth: 1, factKey: "phone", tags: ["basics", "contact"],
    question: "What is the best phone number to call you on, including the country code, and can recruiters leave voicemails?",
    hint: "Mobile number with +44 prefix, plus whether you answer unknown numbers or prefer messages." },
  { id: "id-address", section: "identity", depth: 1, factKey: "address", tags: ["basics"],
    question: "What is your current postal address, and is it a term-time or home address?",
    hint: "Full postcode. State clearly which address applies during the placement period if different." },
  { id: "id-linkedin", section: "identity", depth: 1, factKey: "linkedin", tags: ["basics", "online"],
    question: "Do you have a LinkedIn profile or other public professional page, and how up to date is it?",
    hint: "A URL, and an honest note on whether it reflects your current experience and projects." },
  { id: "id-pitch", section: "identity", depth: 2, tags: ["summary", "pitch"],
    question: "If you had thirty seconds to introduce yourself to a senior banker at a networking event, what would you say?",
    hint: "Who you are, what you study, one concrete thing you have done, and why you are talking to them. Under 80 words." },
  { id: "id-misread", section: "identity", depth: 2, tags: ["self-perception"],
    question: "What do people most often misunderstand about you when they first meet you?",
    hint: "A specific, honest gap between first impression and reality, with an example of how you show the real version." },
  { id: "id-path", section: "identity", depth: 3, tags: ["background", "self-awareness"],
    question: "Which part of your background do you tend to downplay in applications, and why do you think you do that?",
    hint: "A genuine experience or trait you undersell, the reason behind it (e.g. fear of seeming less qualified), and how you now present it." },

  // ---------- logistics ----------
  { id: "log-right-to-work", section: "logistics", depth: 1, factKey: "right_to_work_uk", tags: ["eligibility", "visa"],
    question: "What is your right-to-work status in the UK, and will you need sponsorship now or in the future?",
    hint: "Exact status (e.g. British citizen, settled status, Graduate visa, student visa with work limits) and any sponsorship need, stated plainly." },
  { id: "log-start-date", section: "logistics", depth: 1, factKey: "start_date", tags: ["availability", "dates"],
    question: "What is the earliest date you could start a placement or job, and what is the latest?",
    hint: "Specific dates or months, and whether they are firm or flexible." },
  { id: "log-term-availability", section: "logistics", depth: 1, factKey: "term_availability", tags: ["availability", "study"],
    question: "How do your exams, term dates and deadlines affect when you can work, and which weeks are fixed?",
    hint: "The exact fixed commitments (exam weeks, dissertation submission, resit dates) and when the time is free." },
  { id: "log-locations", section: "logistics", depth: 1, factKey: "preferred_locations", tags: ["location", "preferences"],
    question: "Which cities or offices are you willing to work in, and which are you not able to reach?",
    hint: "A short ranked list (e.g. London, Edinburgh, Manchester) with a note on commute or relocation limits." },
  { id: "log-salary", section: "logistics", depth: 1, factKey: "salary_expectation", tags: ["pay", "expectations"],
    question: "What salary or hourly rate do you expect for this type of role, and how did you arrive at that figure?",
    hint: "A realistic range tied to the sector and scheme, with the basis for it (published rates, peers, living costs)." },
  { id: "log-adjustments", section: "logistics", depth: 1, factKey: "adjustments", tags: ["accessibility", "support"],
    question: "Do you need any reasonable adjustments during recruitment or at work, and what would make them work for you?",
    hint: "Whether you have a disability, condition or need you choose to disclose, the adjustment that helps, and how you want it handled. It is fine to answer 'none'." },
  { id: "log-how-heard", section: "logistics", depth: 1, factKey: "how_heard", tags: ["sourcing", "outreach"],
    question: "How did you first hear about this opportunity or this employer?",
    hint: "The specific channel (careers fair, a named society speaker, a friend, LinkedIn post) so you can track which sources work." },
  { id: "log-relocate", section: "logistics", depth: 3, tags: ["relocation", "flexibility"],
    question: "If the best offer you received required moving city at short notice mid-term, what would have to be true for you to say yes?",
    hint: "Concrete conditions (housing, money, course impact, partner or family, visa), and an honest line on what would make you decline." },

  // ---------- education ----------
  { id: "edu-school", section: "education", depth: 1, factKey: "school", tags: ["schooling"],
    question: "Which sixth form or college did you attend, and what did you study there?",
    hint: "School name, qualifications taken (A-levels, BTECs, IB, Scottish Highers) and the grades you achieved." },
  { id: "edu-uni", section: "education", depth: 1, factKey: "university", tags: ["university"],
    question: "Which university do you study at, and in which city?",
    hint: "Full university name and campus, and whether you are on a placement year or a standard route." },
  { id: "edu-degree", section: "education", depth: 1, factKey: "degree", tags: ["degree"],
    question: "What is the full title of your degree, and is it a single or joint honours?",
    hint: "Exact degree title (e.g. BSc Economics and Finance, BA Politics and Economics), and the other subject if joint." },
  { id: "edu-grade", section: "education", depth: 1, factKey: "expected_grade", tags: ["grades", "results"],
    question: "What classification or grade do you currently hold or expect, and how is it calculated?",
    hint: "Current average or classification and the expected outcome, e.g. 'averaging 68 across years two and three, expecting a 2:1'." },
  { id: "edu-grad-year", section: "education", depth: 1, factKey: "grad_year", tags: ["timeline", "graduation"],
    question: "When do you graduate, and what do you plan to do in the twelve months after that?",
    hint: "Month and year of graduation, plus whether you are seeking a graduate role, further study or a gap." },
  { id: "edu-modules", section: "education", depth: 2, tags: ["modules", "coursework"],
    question: "Which modules have shaped how you think about finance or your subject most, and why?",
    hint: "Two or three named modules, the specific idea that stuck, and an example of applying it outside the lecture hall." },
  { id: "edu-grade-trend", section: "education", depth: 2, tags: ["grades", "reflection"],
    question: "How did your grades change across your degree, and what explains that shape?",
    hint: "The actual trend with numbers, the cause (workload, a move, a change of approach), and what you did about it." },
  { id: "edu-dissertation", section: "education", depth: 2, tags: ["dissertation", "research"],
    question: "What was your dissertation or final-year project about, and what was the main finding or deliverable?",
    hint: "The question in one sentence, the method (data, model, case study), the result, and its word count or scope." },
  { id: "edu-awards", section: "education", depth: 1, tags: ["awards", "prizes"],
    question: "What prizes, scholarships, bursaries or academic distinctions have you received, and what were the criteria?",
    hint: "Name, year, value if relevant, and how many people were eligible or selected." },
  { id: "edu-worst-result", section: "education", depth: 3, tags: ["grades", "failure", "reflection"],
    question: "Which result are you least proud of, what went wrong, and what did you change afterwards?",
    hint: "An honest cause (not just 'bad luck'), the specific habit or method you changed, and evidence it worked on later work." },
  { id: "edu-own-vs-course", section: "education", depth: 3, tags: ["learning", "independence"],
    question: "Beyond the syllabus, what have you taught yourself in your degree, and how did you check you actually understood it?",
    hint: "A topic you learned independently, the resource or method used, and a test you put yourself through to verify it." },

  // ---------- experience ----------
  { id: "exp-jobs", section: "experience", depth: 1, tags: ["work-history", "jobs"],
    question: "List your paid jobs so far, with employer, role, dates and hours per week.",
    hint: "Each job in one line with dates and hours. Paid work counts even if unrelated to your target sector." },
  { id: "exp-internship", section: "experience", depth: 1, tags: ["internship", "work-experience"],
    question: "Have you completed any internships, insight days or spring weeks, and where?",
    hint: "Employer, dates, length and whether it was a formal programme. Note if it was an insight day with no task." },
  { id: "exp-day", section: "experience", depth: 2, tags: ["role", "day-to-day"],
    question: "Describe a typical day or week in your most relevant role. What did you spend most of your time on?",
    hint: "Concrete tasks, tools and people involved, with rough time split. Specific detail beats a job description." },
  { id: "exp-volunteering", section: "experience", depth: 1, tags: ["volunteering", "community"],
    question: "What voluntary or unpaid work have you done, and roughly how long did you commit to it?",
    hint: "Organisation, role, time commitment and whether it had a defined output or beneficiary." },
  { id: "exp-achievement", section: "experience", depth: 2, tags: ["achievement", "results"],
    question: "What is the single biggest measurable result you delivered in a job or volunteering role?",
    hint: "The number (money, time saved, customers, percentage, headcount), what you did to move it, and the baseline." },
  { id: "exp-feedback", section: "experience", depth: 2, tags: ["feedback", "performance"],
    question: "What did a manager or supervisor say about your work that you still remember?",
    hint: "The actual words or close to them, the context, and what it taught you about how you come across." },
  { id: "exp-team-vs-me", section: "experience", depth: 3, tags: ["ownership", "responsibility"],
    question: "On your most significant piece of team work, what were you personally responsible for, as opposed to the team as a whole?",
    hint: "Separate your own deliverable and decisions from the group output. Name what you owned end to end." },
  { id: "exp-mistake", section: "experience", depth: 3, tags: ["mistake", "accountability"],
    question: "What is the biggest mistake you made at work, and how did you find out, and who did you tell?",
    hint: "A real error with its consequence, how and when you noticed, who you told first, and the process you fixed." },
  { id: "exp-missed", section: "experience", depth: 3, tags: ["limits", "ambition"],
    question: "What did you ask to do at work that you were not allowed to do, and what did you do instead?",
    hint: "A specific request, the reason it was declined, and the alternative you took that still moved things forward." },
  { id: "exp-tools", section: "experience", depth: 1, tags: ["tools", "software"],
    question: "Which software, systems or tools did you use regularly in your jobs, and at what level?",
    hint: "Named tools (Excel, Bloomberg, SAP, Salesforce, Canva) with a level: used, built with, or taught others." },

  // ---------- projects ----------
  { id: "proj-main", section: "projects", depth: 1, tags: ["projects", "portfolio"],
    question: "What is the project you are most proud of, and what was it for?",
    hint: "Name, purpose, who it was for, time frame, and your role in one sentence." },
  { id: "proj-dataset", section: "projects", depth: 1, tags: ["data", "analysis"],
    question: "If your project used data, where did it come from and how big was it?",
    hint: "Source (public dataset, scraped, company provided), size, time period, and any cleaning you had to do." },
  { id: "proj-outcome", section: "projects", depth: 2, tags: ["outcome", "impact"],
    question: "What did the project actually produce, and how did you know it worked?",
    hint: "A tangible output (model, report, app, event, pitch) plus evidence: a metric, a user comment, a grade or a decision it changed." },
  { id: "proj-side", section: "projects", depth: 1, tags: ["side-project", "personal"],
    question: "What have you built or started outside your coursework, even if it stayed small?",
    hint: "A personal project, blog, trading simulation, website or model, with the date it started and whether it is still live." },
  { id: "proj-users", section: "projects", depth: 2, tags: ["users", "stakeholders"],
    question: "Who used or was affected by your work, and how did you find out what they actually needed?",
    hint: "The real audience, how you gathered requirements (interviews, survey, observation), and one change you made because of them." },
  { id: "proj-decision", section: "projects", depth: 3, tags: ["decisions", "trade-offs"],
    question: "What was the hardest technical or methodological decision on your project, and what did you give up to make it?",
    hint: "The options you compared, the trade-off you accepted, and why you would or would not make the same choice again." },
  { id: "proj-own-part", section: "projects", depth: 3, tags: ["ownership", "credit"],
    question: "On a group project, which parts did you do yourself, and which parts were you responsible for but did not do personally?",
    hint: "Be exact about the split. Name the parts you designed, wrote, presented, or checked, and the parts you coordinated." },
  { id: "proj-abandoned", section: "projects", depth: 3, tags: ["failure", "learning"],
    question: "Which project did you abandon or badly underestimate, and what did you learn from stopping?",
    hint: "The scope or planning error, the moment you decided to stop, and a concrete rule you now follow." },

  // ---------- skills ----------
  { id: "skill-excel", section: "skills", depth: 1, tags: ["excel", "technical"],
    question: "How would you rate your Excel skills, and which functions or features do you use most?",
    hint: "A level (basic, intermediate, advanced) with examples: pivot tables, lookups, Power Query, VBA, financial modelling." },
  { id: "skill-programming", section: "skills", depth: 1, tags: ["coding", "technical"],
    question: "Which programming languages or statistical packages have you used, and for what?",
    hint: "Languages (Python, R, SQL, JavaScript, Stata) with the longest project or job where you used each." },
  { id: "skill-languages", section: "skills", depth: 1, factKey: "languages_spoken", tags: ["languages"],
    question: "Which languages can you speak, read or write, and at what level?",
    hint: "Each language with a level (native, fluent, working, basic) and a qualification or a real situation where you used it." },
  { id: "skill-certs", section: "skills", depth: 1, tags: ["certifications", "courses"],
    question: "Which certifications or online courses have you completed, and when?",
    hint: "Exact name, provider, completion date and whether the certificate is verifiable." },
  { id: "skill-recent", section: "skills", depth: 2, tags: ["learning", "recent"],
    question: "What new skill or tool have you picked up in the last six months, and how did you learn it?",
    hint: "The skill, the learning method (course, project, reading), and the first real task where you used it." },
  { id: "skill-proof", section: "skills", depth: 2, tags: ["evidence", "proof"],
    question: "Where have you used your most important technical skill in a way someone else could check?",
    hint: "A link, a repository, a model, a presentation or a named project that shows the skill rather than claiming it." },
  { id: "skill-weakest", section: "skills", depth: 3, tags: ["gaps", "self-awareness"],
    question: "Which skill that this sort of role expects do you currently have least of, and what is your plan for it?",
    hint: "Name the real gap (e.g. accounting principles, pivot tables, a language), how you know, and a dated plan to close it." },
  { id: "skill-communication", section: "skills", depth: 2, tags: ["communication", "presenting"],
    question: "How do you explain complicated information to someone who does not know the subject?",
    hint: "A real example where you simplified something technical, the tool or structure you used, and how you checked they understood." },

  // ---------- stories ----------
  { id: "story-leadership", section: "stories", depth: 2, tags: ["leadership", "star"],
    question: "Tell me about a time you led a group or team that had no formal authority over the people in it.",
    hint: "Situation, your specific actions to get buy-in, the result with a number, and what you would repeat." },
  { id: "story-teamwork", section: "stories", depth: 2, tags: ["teamwork", "star"],
    question: "Describe a time a team you were in did well because of how people worked together, not just what they knew.",
    hint: "The team dynamic, your role in it, a moment you helped it work, and the measurable outcome." },
  { id: "story-initiative", section: "stories", depth: 2, tags: ["initiative", "star"],
    question: "When did you start something nobody asked you to do? What made you do it?",
    hint: "The gap you saw, the first step you took without permission, the result, and how it was received." },
  { id: "story-pressure", section: "stories", depth: 2, tags: ["pressure", "deadlines", "star"],
    question: "Tell me about a time you had to deliver under serious time pressure. How did you decide what to drop?",
    hint: "The deadline and stakes, the prioritisation logic, what you cut, and the outcome against the deadline." },
  { id: "story-persuasion", section: "stories", depth: 2, tags: ["persuasion", "influence", "star"],
    question: "Describe a time you changed someone's mind on something important to you or to a group.",
    hint: "The original view, the evidence or framing you used, how you handled their objections, and whether it stuck." },
  { id: "story-conflict", section: "stories", depth: 3, tags: ["conflict", "star"],
    question: "Tell me about a real disagreement with a colleague or friend where you were partly wrong. What did each of you actually want?",
    hint: "The specific disagreement, the other person's position in their words, the part you got wrong, and how you repaired it." },
  { id: "story-failure", section: "stories", depth: 3, tags: ["failure", "star"],
    question: "Tell me about a time you failed at something you cared about. What did you do in the first 24 hours after?",
    hint: "The failure stated plainly, your immediate reaction, who you told, the root cause you found, and the change that followed." },
  { id: "story-ethics", section: "stories", depth: 3, tags: ["ethics", "dilemma", "star"],
    question: "Describe a time you faced an ethical dilemma where doing the right thing was costly. What did you actually do?",
    hint: "The competing pressures (money, loyalty, rules), the decision you made and why, and what it cost you personally." },
  { id: "story-learning", section: "stories", depth: 2, tags: ["learning", "speed", "star"],
    question: "Tell me about a time you had to become productive in something new very quickly.",
    hint: "The unfamiliar area, how fast you got to useful output (days, not months), the method you used to learn, and the result." },
  { id: "story-beyond", section: "stories", depth: 2, tags: ["going-beyond", "star"],
    question: "Describe a time you did more than the brief asked for. Was it worth it?",
    hint: "What the brief said, what you added, the cost in time or money, and whether anyone actually used the extra." },

  // ---------- motivation ----------
  { id: "mot-why-career", section: "motivation", depth: 2, tags: ["career-choice", "motivation"],
    question: "Why do you want to work in your target career, rather than a related one?",
    hint: "A specific reason rooted in experience, not a generic answer. Name what you have seen or done that points there." },
  { id: "mot-why-finance", section: "motivation", depth: 2, tags: ["why-finance", "motivation"],
    question: "Why finance, banking or economics specifically? What do you find interesting about the day-to-day work?",
    hint: "A concrete part of the work (e.g. building models, deal analysis, risk) that appeals and a reason you have tested that interest." },
  { id: "mot-why-sector", section: "motivation", depth: 2, tags: ["sector", "motivation"],
    question: "Which part of the sector would you not want to work in, and why?",
    hint: "A specific area you would decline (e.g. retail banking sales, high-frequency trading), and the reason that shows judgement." },
  { id: "mot-why-firm", section: "motivation", depth: 2, tags: ["firm", "company"],
    question: "What is it about this type of firm, rather than another, that appeals to you?",
    hint: "Size, culture, client base, graduate programme or product, with something you verified from a real source." },
  { id: "mot-goal", section: "motivation", depth: 2, tags: ["career-goals", "ambition"],
    question: "Where do you want to be five years after graduating, and what would count as a good outcome?",
    hint: "A realistic role and scope, a measure of success you would recognise, and how the placement fits in." },
  { id: "mot-placement", section: "motivation", depth: 2, tags: ["placement", "learning-goals"],
    question: "What do you want to get out of this placement or internship that you cannot get elsewhere?",
    hint: "Two or three specific skills, exposures or relationships you are aiming for, and how you will measure progress." },
  { id: "mot-industry", section: "motivation", depth: 2, tags: ["industry", "knowledge"],
    question: "How does the business or firm you are applying to make money, and what do you think it does well?",
    hint: "Revenue model, key clients or products, a recent result or strategy, and a view you hold about it." },
  { id: "mot-news", section: "motivation", depth: 2, tags: ["current-affairs", "commercial-awareness"],
    question: "What economic or market news from the last month do you think matters most for your target sector?",
    hint: "One specific story with the number or fact, why it matters to a firm or client, and your own view on what happens next." },
  { id: "mot-news-changed", section: "motivation", depth: 3, tags: ["current-affairs", "views"],
    question: "What recent event changed your view on something important, and what did you believe before?",
    hint: "The event, the earlier belief stated honestly, the evidence that moved you, and whether you still think you were right." },
  { id: "mot-dealbreaker-career", section: "motivation", depth: 3, tags: ["career-choice", "doubt"],
    question: "What evidence would make you decide your chosen career is not for you?",
    hint: "Specific signals (work you dislike, skills you cannot build, a pay or lifestyle limit) and how you would test them early." },

  // ---------- values ----------
  { id: "val-work-matters", section: "values", depth: 2, tags: ["values", "work"],
    question: "What do you need from a job for it to feel worthwhile to you?",
    hint: "Two or three concrete needs (ownership, client contact, learning, pay, purpose), each linked to something you have experienced." },
  { id: "val-manager", section: "values", depth: 2, tags: ["manager", "working-style"],
    question: "What does a good manager do for you, and what do you do for them in return?",
    hint: "Specific behaviours (clear feedback, time to ask questions) and what you commit to in return (updates, ownership, quality)." },
  { id: "val-team", section: "values", depth: 2, tags: ["team", "culture"],
    question: "Describe the ideal team you would want to work in day to day.",
    hint: "Team size, mix of seniority, pace, how disagreement is handled, and an example that shows why that matters to you." },
  { id: "val-pace", section: "values", depth: 2, tags: ["pace", "quality"],
    question: "When a deadline and quality pull against each other, what do you usually do?",
    hint: "Your default, the reasoning behind it, and a time it went the other way and what you learned." },
  { id: "val-recognition", section: "values", depth: 2, tags: ["recognition", "motivation"],
    question: "How do you like to be recognised for good work, and how do you handle it when you are not?",
    hint: "Your preference (public praise, private thanks, promotion), and an example where recognition was missing and how you responded." },
  { id: "val-ethics", section: "values", depth: 3, tags: ["ethics", "integrity"],
    question: "What would you refuse to do at work even if your manager told you to, and what would you do instead?",
    hint: "A specific line (e.g. misreporting numbers, misleading a client), the escalation path you would take, and who you would tell." },
  { id: "val-dealbreaker", section: "values", depth: 3, tags: ["dealbreakers", "culture"],
    question: "What is a workplace behaviour you have seen that you could not work alongside for a year?",
    hint: "The specific behaviour, why it matters to you, and an honest note on whether your reaction is fair to others." },
  { id: "val-success", section: "values", depth: 2, tags: ["success", "definition"],
    question: "How would you define a successful first year in your first job?",
    hint: "Measurable and personal markers (skills, responsibilities, relationships) that show you are growing, not just surviving." },

  // ---------- strengths ----------
  { id: "str-top", section: "strengths", depth: 2, tags: ["strengths", "self-assessment"],
    question: "What are your two strongest professional strengths, and what is the evidence for each?",
    hint: "Two named strengths, each backed by a specific example with an outcome. Avoid adjectives without proof." },
  { id: "str-others", section: "strengths", depth: 2, tags: ["strengths", "perspective"],
    question: "What would a close colleague or friend say is your strongest quality, and would you agree?",
    hint: "The strength as others see it, the moment they cited, and whether your own view differs." },
  { id: "str-weakness", section: "strengths", depth: 3, tags: ["weakness", "self-awareness"],
    question: "What is a weakness you have that has actually cost you something? What did it cost, specifically?",
    hint: "A real weakness (not a disguised strength), the concrete cost (missed deadline, lost trust), and the system you built to manage it." },
  { id: "str-feedback", section: "strengths", depth: 2, tags: ["feedback", "growth"],
    question: "What is the most useful piece of critical feedback you have received, and what did you change because of it?",
    hint: "The feedback in its actual words, the source, the behaviour you changed, and how you know the change held." },
  { id: "str-criticism", section: "strengths", depth: 3, tags: ["feedback", "defensiveness"],
    question: "What criticism did you resist at first, and was the person right?",
    hint: "The criticism, your initial reaction, the point at which you saw it differently, and what you do now when it comes up." },
  { id: "str-energy", section: "strengths", depth: 2, tags: ["energy", "work-style"],
    question: "What kind of tasks give you energy, and which drain it?",
    hint: "Two or three examples of each, grounded in real work, and how you manage the drain tasks." },
  { id: "str-decisions", section: "strengths", depth: 3, tags: ["decision-making", "judgement"],
    question: "When you have to make a decision with incomplete information, how do you decide, and when have you got that wrong?",
    hint: "Your method (frame, data, deadline, reversibility), a case where you decided and were wrong, and what the method now includes." },
  { id: "str-curiosity", section: "strengths", depth: 2, tags: ["curiosity", "self-directed"],
    question: "What is something you have looked into without being asked, and what did you conclude?",
    hint: "The question, the research method, the conclusion, and who you shared it with." },

  // ---------- interests ----------
  { id: "int-hobbies", section: "interests", depth: 1, tags: ["hobbies", "personal"],
    question: "What do you do outside work and study on a regular basis?",
    hint: "Two or three activities with a rough frequency, including anything you are seriously committed to." },
  { id: "int-society", section: "interests", depth: 1, tags: ["societies", "student-life"],
    question: "Which societies, clubs or student groups are you part of, and what is your role in them?",
    hint: "Name, your role (member, committee, founder) and the year you joined or took the role." },
  { id: "int-sport", section: "interests", depth: 1, tags: ["sport", "fitness"],
    question: "Do you play any sport or take part in any physical activity, and at what level?",
    hint: "The sport, the level (casual, club, university, county), and any team or individual achievement." },
  { id: "int-reading", section: "interests", depth: 2, tags: ["reading", "books"],
    question: "What have you read in the last year that was not required for your course, and what did you take from it?",
    hint: "Two or three books, articles or papers, each with one specific idea you still use or disagree with." },
  { id: "int-podcasts", section: "interests", depth: 1, tags: ["news", "media"],
    question: "Which news sources, podcasts or newsletters do you follow regularly?",
    hint: "Named sources you actually read (FT, Economist, Money Podcast, Bank Underground) and how often." },
  { id: "int-commercial", section: "interests", depth: 2, tags: ["commercial-awareness", "markets"],
    question: "Which business or market topic do you find yourself thinking about most, and what is your current view?",
    hint: "The topic (e.g. interest rates, AI capex, energy transition), your stated view, and what evidence would change it." },
  { id: "int-passion", section: "interests", depth: 2, tags: ["passion", "projects"],
    question: "What would you spend a free Saturday on if no one was paying or assessing you?",
    hint: "A specific activity that shows what you enjoy building, learning or solving, and how often you have done it." },
  { id: "int-unusual", section: "interests", depth: 3, tags: ["personal", "identity"],
    question: "What is an interest of yours that most people in your industry would find surprising, and what does it say about you?",
    hint: "A real, specific interest, the link to how you work, and a sentence that makes the interviewer remember you." },

  // ---------- voice ----------
  { id: "voice-friend", section: "voice", depth: 2, tags: ["voice", "explanation"],
    question: "Explain something you know well to a friend who has never studied it. Use your own words and keep it casual.",
    hint: "A complete explanation in your natural speaking style, with one analogy. Shows how you explain without jargon." },
  { id: "voice-best-day", section: "voice", depth: 2, tags: ["voice", "reflection"],
    question: "Describe your best day of work or study so far. What made it good?",
    hint: "A specific day, what happened hour by hour if relevant, and the thing that made it feel right. Use the details you remember." },
  { id: "voice-room", section: "voice", depth: 2, tags: ["voice", "observation"],
    question: "Describe the most interesting room you have walked into, and what you noticed about the people in it.",
    hint: "Concrete sensory detail, the people and their roles, and one observation that tells the reader what you pay attention to." },
  { id: "voice-opinion", section: "voice", depth: 2, tags: ["voice", "opinion"],
    question: "Give a view you hold on a topic that people often disagree with you about, and defend it briefly.",
    hint: "A clear position, the strongest reason for it, and the counter-argument you take seriously." },
  { id: "voice-lesson", section: "voice", depth: 2, tags: ["voice", "learning"],
    question: "Write about something you learned this year that you did not expect to learn.",
    hint: "The lesson stated plainly, the moment it happened, and what you do differently now." },
  { id: "voice-friend-describe", section: "voice", depth: 2, tags: ["voice", "self-description"],
    question: "If a close friend described the way you talk and write to someone else, what would they say?",
    hint: "Honest, specific traits (direct, dry humour, over-explains) and an example that shows each one." },
  { id: "voice-plain-mistake", section: "voice", depth: 3, tags: ["voice", "accountability"],
    question: "Explain a mistake you made without using any soft language like 'learning opportunity'. What happened, and what was your part?",
    hint: "Plain statements of what you did, what it caused, and what you would do differently. No passive phrasing that hides your role." },
  { id: "voice-stranger", section: "voice", depth: 1, tags: ["voice", "introduction"],
    question: "Describe yourself in three sentences to a stranger who will read your application for the first time.",
    hint: "Three short sentences: what you study, what you have done, and what you want next. Written as you would say it." },
];
